### ISSUE TITLE
Adapter uses image of Echo 2 for Echo Input

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#289]
Echo Input (device type A1JJ0KFC4ZPNJ3) uses wrong Image.

Here is one you can use. =)

![echo_input](https://user-images.githubusercontent.com/40962599/63118540-5ac35700-bf9e-11e9-9baa-f8a12c794e82.png)

PS: Oops, of Course it uses the Image of "Echo", not "Echo 2" ;)

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)

**Comment by padrino-x** [comment]
Are you in a hurry?
4 hours after "please check" the "close"? =)
Well, it seems not fixed. The image displayed here is /img/info-big.png instead of mine above.

**Comment by Apollon77** [comment]
Upload please and make sure the instance got restarted!! And clear browser cache.

**Comment by padrino-x** [comment]
Ok, upload fixed it. Thanks.
